# Turns the shared simulation source and the GPU kernels into C strings compiled into brtrain,
# so the program is a single self-contained executable.
function(embed var file)
  file(READ "${file}" hex HEX)
  string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," hex "${hex}")
  file(APPEND "${OUT}" "static const char ${var}_data[] = {${hex}0x00};\nconst char* ${var} = ${var}_data;\n")
endfunction()
file(WRITE "${OUT}" "/* generated from src/sim_core.h and src/kernels — do not edit */\n")
embed(BR_SRC_SIM_CORE "${SRC}/sim_core.h")
embed(BR_SRC_METAL "${SRC}/kernels/metal_kernel.metal")
embed(BR_SRC_OPENCL "${SRC}/kernels/opencl_kernel.cl")
embed(BR_UI_HTML "${SRC}/../web/index.html")
# three.js (MIT, see web/vendor/three-LICENSE.txt) is served by the app itself: the page loads nothing from the internet
embed(BR_V_THREE "${SRC}/../web/vendor/three.module.js")
embed(BR_V_ORBIT "${SRC}/../web/vendor/addons/controls/OrbitControls.js")
embed(BR_V_LINE2 "${SRC}/../web/vendor/addons/lines/Line2.js")
embed(BR_V_LINEMAT "${SRC}/../web/vendor/addons/lines/LineMaterial.js")
embed(BR_V_LINEGEO "${SRC}/../web/vendor/addons/lines/LineGeometry.js")
embed(BR_V_SEG2 "${SRC}/../web/vendor/addons/lines/LineSegments2.js")
embed(BR_V_SEGGEO "${SRC}/../web/vendor/addons/lines/LineSegmentsGeometry.js")
